title: Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Raymon van Dinter
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raymon van Dinter # add your name
author-img: raymon-van-dinter.jpg # add your photo
about-author: I am a Data Science student at Wageningen University. Always hungry to keep learning. # add description
social-github: rvdinter # add your Github handle
social-linkedin: raymonvandinter # add your Linkedin handle
social-email: r.dinter.rvd@gmail.com

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
